### ISSUE TITLE
--list-channels problem

### ISSUE THREAD

**Issue by MikeB2013** [honir/tv_grab_uk_atlas#1]
First of all thanks for this grabber, it seems to work great apart for --list-channels which gives errors e.g. 
 tv_grab_uk_atlas --list-channels
Use of uninitialized value $platform_title in concatenation (.) or string at /usr/bin/tv_grab_uk_atlas line 649.
Use of uninitialized value $region_title in concatenation (.) or string at /usr/bin/tv_grab_uk_atlas line 650.
Use of uninitialized value $selected_region in concatenation (.) or string at /usr/bin/tv_grab_uk_atlas line 658.
Fetching channels:   0% [                                                                                              ]404 Not Found
Fetching channels: 100% [==============================================================================================]<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv generator-info-name="tv_grab_uk_atlas"></tv>

The following 3 lines are appended to the previously created .conf file at the end:

api-key=/home/mike/.xmltv/supplement/tv_grab_uk_atlas/atlasAPIkey
platform-title=
region-title=

--list-channels works on same system (13.04 Ubuntu raring) using tv_grab_uk_rt, so xmltv (0.5.63) is working properly. My version of perl is 5.14.2.

Mike

**Comment by honir** [comment]
Thanks for the report. Yes it seems --list-channels doesn't work at the moment, because of the way you have to select a 'platform' first then a 'region' before you can get to the channels.  The standard XMLTV "--list-channels" doesn't seem to cope with that, and I'm not happy with listing all channels for _all_ regions for _all_ platforms! 

If you check the 'data' subdir you'll find a list of the platforms (platforms.txt) and regions (regions.txt) with their channels.

Alternatively just run --configure and select the options you want.

**Comment by MikeB2013** [comment]
I understand the problem - vast amount of data for all platforms and regions. How about just displaying all the channels including display name for the platform and region in the .conf file (either the default of tv_grab_uk_atlas.conf or a user specified --config-file) ? This would show the display name of the channel id for every channel of the specified platform and region e.g
<channel id="cbCZ"><display-name lang="en">ITVHD Meridian</display-name></channel>

Mike

**Comment by honir** [comment]
Yes I need to think about the best way of displaying useful info without putting undue load on the Atlas server. Thinking out loud I might make --list-channels work like --configure so you select a platform and region and display the channels for the one you select.  I think that was the original intention within xmltv for this option (i.e. --list-channels was like a dummy run for --configure).

It's complicated because the channel ids used within Atlas bear no relation to the real world, e.g. cbbf, cbjQ, etc.

In the interim you can view the file map_all.txt (and the 3 sorted versions of it) in the 'data' dir.  This does list all channels for all regions for all platforms (if you really want that ;-) ).

Likewise there are static files for all the separate regions. E.g. look in platforms.txt and select the one you want e.g. cbfK Sky HD.  Then look in regions_Sky_HD.txt and select your region e.g. cbfS North East.  Then look in map_cbfS.txt for the Sky channel numbers available in that region.

**Comment by honir** [comment]
--list-channels is now fixed in v1.008

Thanks again for raising this issue.
